# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e085cad8bc82c6df32aec7069c7e58ca0f9d49508eb11db056bf0d42d38f839dd9ac13fb4ca9dfd4ce2eeecede098984ccf3d46f72ad73909b38be651548ebd7

test:
  secret_key_base: 8afbe75cd4441f7402b78cb53c7c5700906cbab3d8028322d6f4ef25644cb118d5bdf696254adfc23b12b4c7018f93027f357de7c8e6362598d45f57a324b1b2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
